### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/heart_disease_predictor#18]
_Congratulations on finishing milestone 1!
Below I list some specific feedback you can use to improve your project.
I provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread._

**Exploratory data analysis in a literate code document**

- [x]  There are no figure captions. -2
- [x] corr_viz plots were hard to understand. Please improve the visualization -2
- [x] Usage documentation is not satisfactory. -1
- [x] Dependencies are not well documented. versions are missing. -2

**Comment by tzoght** [comment]
Hello @muntakimrafi 
I have one follow up question item 3 on your list, are you referring to the section in the in the 
README.md ? (https://github.com/UBC-MDS/heart_disease_predictor#reproducibility), or something else ?
Thank you

**Comment by muntakimrafi** [comment]
Yes, I am referring to the _reproducibility_ section.
