### ISSUE TITLE
Milestone 3 Meeting Notes

### ISSUE THREAD

**Issue by Natalie-cho** [UBC-MDS/heart_disease_predictor#30]
In attendance: @tzoght @Natalie-cho @Yurui-Feng @elenagan
Scribe: @Natalie-cho 
Proofreader: @Yurui-Feng 

## Topics of discussion:
- [x] Create a Makefile that runs the entire analysis from top to bottom @everyone
- [x] Create scaffolding @tzoght 
- [x] EDA.py @Yurui-Feng 
- [x] Fetch_dataset @tzoght 
- [x] model.py @elenagan 
- [x] pre_process.py @Natalie-cho 
- [x] Add more comments and clean up model.py script @elenagan 
- [x] Try out the environment.yml @everyone

**Comment by elenagan** [comment]
@tzoght The environment.yml file is working for me. It just took a while to solve, but otherwise no issues so far.

**Comment by Natalie-cho** [comment]
The environment.yml seems to be working! As with Elena, it took my computer a long while to solve.

**Comment by Yurui-Feng** [comment]
The makefile script ran smoothly on my computer with no issues. The same also for environment.yml
