### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/heart_disease_predictor#34]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work! 
Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Command line arguments are missing from one or more scripts -3 accuracy
**Comment:** It is better to have your commands fully written out including the input —from and output —to flags. As a user all i would want tot do is copy and paste and not have to go into your script to understand what I should be providing. Secondly, when I run your command as is I get an error because I am within your src directory running the command and the output path is /data/raw/heart.csv which is outside your src so the path should actually be ../data/raw/heart.csv 

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). -2 writing
**Comment:** The command provided has different script names than the script names within src itself which also leads to errors while running the commands. 

- [ ] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added -1 quality
**Comment:** Author and date missing from 2 of your scripts. 

- [ ] The proposal.md file has not been created and moved to the doc directory -2 mechanics

- [ ] The literate code document (R Markdown or Jupyter notebook) does not hide the code that should be hidden from the reader (all, or almost all, code should be hidden in the final rendered document) -1 quality
**Comment:** Code for the tables is shown in the final document. 

- [ ] There are not figure captions. -2 viz

- [ ] Challenging question- Tests arent present for any of the scripts. -7

**Comment by tzoght** [comment]
Hello @aditi48n , thanks for the clear feedback, on the last item, we are using Github Workflows for continuous integration and testing [github workflow actions](https://github.com/UBC-MDS/heart_disease_predictor/actions/workflows/test_branch.yml  ) which tests the whole workflow and scripts on submission. On a conversation I had with Florencia, she said that the task of testing is open ended and left to each team to implemented the way they see it fit.

**Comment by aditi48n** [comment]
Hello @tzoght! Oh Okay, interesting. Let me talk to her about this and get back on the grading. Thank you for bringing this to my attention.

**Comment by tzoght** [comment]
That's awesome, thank you Aditi
