### ISSUE TITLE
Milestone 3 Comments

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/heart_disease_predictor#38]
**Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

# Automating the data-analysis pipeline using Make

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- [ ] The `Makefile` is not well documented **- 2** **quality**
**Comment:** Add documentation for make all and make clean

### Dependencies have been updated (so it include the test libraries)
Good job!
### Project file and directory structure organization
Good job!

###  Analysis can be run reproducibly using documentation provided in the README
- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-2** **mechanics**
**Comment:**  Docopt cannot parse the documentation for some of the scripts. I think the issue is that there should be a empty line between usuage and options in the doucmentation section.

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-4** **quality**
**Comments:** Installing dependencies using conda and the environment.yaml does not work (Conflicting dependencies). Make sure to rerun the whole project from scratch using a new environment to make sure you aren't missing anything. 

# Expectations

### Follows GitHub flow version control workflow
Good job!
### GitHub release

- [ ] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-2** **mechanics**
