### ISSUE TITLE
Dec 7: Milestone 4 Meeting

### ISSUE THREAD

**Issue by Yurui-Feng** [UBC-MDS/heart_disease_predictor#39]
- Dependency diagram of the Makefile @tzoght 
- Write a Docker File @tzoght 
- Use GitHub action to build the docker image @tzoght 
- Instruction to reproduce the project with Docker @tzoght 
- Improve the project per TA feedback @tzoght @Yurui-Feng @Natalie-cho @elenagan 
- Pick 5 peer review feedback @elenagan 
- Improve the project per peer reviews @tzoght @Yurui-Feng @Natalie-cho @elenagan

**Comment by tzoght** [comment]
- [x] Dependency diagram of the Makefile @tzoght
- [x] Write a Docker File @tzoght
- [x] Instruction to reproduce the project with Docker @tzoght

**Comment by elenagan** [comment]
- [ ] Author and date missing from 2 of your scripts @Yurui-Feng 
- [ ] There are not figure captions @Yurui-Feng 
- [ ] I belive the ReadMe file is not updated as there is mismatch in the name of the the Python script used to download data. The Readme file mentions running the script "download_data.py" in the src directory but the src directory does not have this script. Instead there is a "fetch_dataset.py" which I believe is supposed to be used to download the dataset. @Natalie-cho 
- [ ] The generated report has a table that was cut off. You can fix that by reducing the content of the table @elenagan 
- [ ] Since parameter optimization is done for the models, it might be helpful to include the specific parameters being used in the results table for model selection. In this way, we know that the models being compared are already optimized @Natalie-cho
